### ISSUE TITLE
Function is undefined on main.js

### ISSUE THREAD

**Issue by roxnlopez** [roxnlopez/project2#5]
On my front end code, for my Delete route, DevTools are telling me that my updateFavorites function is undefined. I have it as a post function and below that the delete ajax route, where I am calling updateFavorites to update the list. 
I have googled undefined functions and mongoose crud examples to no avail.

**Comment by stefems** [comment]
Your delete route is defined in back-end JS code. Your front-end code is composed of JS files that use AJAX to send requests to those routes defined in your back-end. You're saying that you have a function in your front-end code that is undefined? What file and line number does the error specify? Have you looked in that file and confirmed that the function was defined? How did you define the function? Is it misspelled? Remember that there is a distinction between using var/let and using the function keyword. Read more here: https://stackoverflow.com/questions/336859/var-functionname-function-vs-function-functionname

**Comment by stefems** [comment]
Have you solved the undefined function issue? What have you done so far to resolve it?
